name: formalingua
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter    
  hotkey_manager: ^0.2.3
  clipboard: ^0.1.3
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  ffi: ^2.1.3
  win32: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env